### PR TITLE
Make chart and text canvas right-click menus the same

### PR DESCRIPTION
**Pull request by jessyec-s**
This patch makes the text and chart canvases' right click menus the same.

### CODE REVIEW

**Comment by jessyec-s** [comment]
It seems that the "Input Methods" tab is not synced between the chart and text canvases - when one is modified in a menu it is not reflected in the other one.  Ill look into this.

**Comment by jessyec-s** [comment]
So the "Input Methods" option on the menu is a jface feature.  It seems that it should not even be present on the chartChanvas menu because there is no text on the canvas anyway.  But I cannot figure out how to remove it from the menu either.

**Comment by aptmac** [comment]
Neat, I also segfault when going "Input Methods" -> Wayland.

From a bit of digging, this appears to be a Linux (GTK) specific menu item .. I can vouch that the solution listed here [0] will work at removing the menu item.

In `ChartAndPopupTableUI`:

`Display.getCurrent().setData("org.eclipse.swt.internal.gtk.noInputMethod",true);`

2019-12-10-124648_341x260_scrot


[0] https://stackoverflow.com/questions/4460736/eclipse-rcp-remove-context-menu-entry-input-methods

**Comment by jessyec-s** [comment]
Ok I have removed "Input Methods" from the menu in https://github.com/aptmac/jmc/pull/52/commits/8c0c8fca2a1b8e0de2e540938ac65703dd80c070. 

Also this removes the option from all chart menus in the application - not sure if this is desired or not.

**Comment by aptmac** [comment]
> Also this removes the option from all chart menus in the application - not sure if this is desired or not.

That's a valid point.. I think for the Threads Page in particular it might be okay to remove it because we cannot sync it between the two context menus. I'm thinking that maybe the `Display.getCurrent.setData(..)` could be added to the ThreadsPage constructor instead, and can be reverted in the `saveTo()` which is called when `JfrEditor` detects navigation to another page. This way the menu item can be removed for the threads page.

Also it looks like the value supplied to `setData()` has to be `null`?.. using `false` isn't re-enabling the menu item on other context menus for me.

**Comment by jessyec-s** [comment]
Ok I have made it so that 'Input methods' only appears on the Threads Page menus (https://github.com/aptmac/jmc/pull/52/commits/f3cad09b4acb9795865367f41913effdb1db3258)

**Comment by aptmac** [comment]
Yesterday I talked to ericwill about the "Input Methods" context menu items, and he told me that it's removed in a future version of eclipse. The later commits on this PR can be revisited when we eventually update to that version.

**Pull request merged**
